/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tpSurClasses.vue;

import java.util.ArrayList;
import javax.swing.DefaultListModel;
import tpSurClasses.Eleve;
import tpSurClasses.Groupe;

/**
 *
 * @author t.chaumette
 */
public class GestionGroupe extends javax.swing.JFrame {
    private Modele modele;
    /**
     * Creates new form GestionGroupe
     */
    public GestionGroupe() {
        modele = new Modele();
        initComponents();
        loadModele();
    }

    private void saveModele()
    {
        try
        {
            RessouceManager.save(this.modele, "modele.save");
        }
        catch (Exception e)
        {
            System.out.println("Erreur lors de la sauvegarde du modele : " + e.getMessage());
        }
    }

    private void loadModele()
    {
        try
        {
            this.modele = (Modele) RessouceManager.load("modele.save");
            updateComponents();
        }
        catch (Exception e)
        {
            System.out.println("Erreur lors du chargement du modele : " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addText = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        addGroupe = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        addEleve = new javax.swing.JList<>();
        addEleveGroupe = new javax.swing.JButton();
        groupeText = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        groupeGroupe = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        groupeEleve = new javax.swing.JList<>();
        groupeAfficher = new javax.swing.JButton();
        groupeSuppr = new javax.swing.JButton();
        eleveText = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        eleveEleve = new javax.swing.JList<>();
        jScrollPane6 = new javax.swing.JScrollPane();
        eleveGroupe = new javax.swing.JList<>();
        eleveAfficher = new javax.swing.JButton();
        eleveSuppr = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        addText.setText("ajouter un élève à un groupe");

        addGroupe.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(addGroupe);

        addEleve.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(addEleve);

        addEleveGroupe.setText("ajouter");
        addEleveGroupe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addEleveGroupeActionPerformed(evt);
            }
        });

        groupeText.setText("voir les éleves dans chaque groupe");

        groupeGroupe.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane4.setViewportView(groupeGroupe);

        groupeEleve.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(groupeEleve);

        groupeAfficher.setText("afficher");
        groupeAfficher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                groupeAfficherActionPerformed(evt);
            }
        });

        groupeSuppr.setText("supprimer");
        groupeSuppr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                groupeSupprActionPerformed(evt);
            }
        });

        eleveText.setText("voir les groupes d'un élève");

        eleveEleve.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane5.setViewportView(eleveEleve);

        eleveGroupe.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane6.setViewportView(eleveGroupe);

        eleveAfficher.setText("afficher");
        eleveAfficher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eleveAfficherActionPerformed(evt);
            }
        });

        eleveSuppr.setText("supprimer");
        eleveSuppr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eleveSupprActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(addEleveGroupe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(90, 90, 90)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(groupeText, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(86, 86, 86)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                                    .addComponent(groupeAfficher, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(groupeSuppr))))
                    .addComponent(addText))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                            .addComponent(eleveAfficher, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(eleveSuppr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(eleveText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(30, 30, 30))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addText)
                    .addComponent(groupeText, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eleveText))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(addEleveGroupe)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(groupeSuppr)
                                .addComponent(groupeAfficher))))
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(eleveSuppr)
                            .addComponent(eleveAfficher))))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void updateComponents()
    {
        updateComponentsAdd();
        initComponentsGG();
        updateComponentsGroupeEleve(new ArrayList<Eleve>());
        initComponentsEE();
        updateComponentsEleveGroupe(new ArrayList<Groupe>());


    }


    

    private void updateComponentsAdd()
    {
        DefaultListModel model = new DefaultListModel();
        addGroupe.setModel(model);

        for (Groupe g : modele.getGroupes())
        {
            model.addElement(g.getNomGroupe());
        }

        DefaultListModel model2 = new DefaultListModel();
        addEleve.setModel(model2);

        for (Eleve e : modele.getEleves())
        {
            model2.addElement(e.getNom());
        }
    }

    private void addEleveGroupeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addEleveGroupeActionPerformed
        String eleve = addEleve.getSelectedValue();
        String groupe = addGroupe.getSelectedValue();

        // Ajouter l'élève au groupe
        modele.addEleveGroupe(groupe, eleve);
        saveModele();

        updateComponents();
    }



// --------------------------------------------------------------------------------------------------------------------------------------------------------



    // initialise les composants de la liste des groupes
    private void updateComponentsGroupeEleve(ArrayList<Eleve> listeEleve)
    {
        DefaultListModel model = new DefaultListModel();
        groupeEleve.setModel(model);

        for (Eleve e : listeEleve)
        {
            model.addElement(e.getNom());
        }
    }

    private void initComponentsGG()
    {
        DefaultListModel model = new DefaultListModel();
        groupeGroupe.setModel(model);

        for (Groupe g : modele.getGroupes())
        {
            model.addElement(g.getNomGroupe());
        }
    }
    

    private void groupeAfficherActionPerformed(java.awt.event.ActionEvent evt) {
        String groupe = groupeGroupe.getSelectedValue();
        Groupe g = modele.getGroupe(groupe);
        saveModele();
        updateComponentsGroupeEleve(g.getListeEleve());
    }

    private void groupeSupprActionPerformed(java.awt.event.ActionEvent evt) {
        String groupe = groupeGroupe.getSelectedValue();
        String eleve = groupeEleve.getSelectedValue();
        modele.removeEleveGroupe(groupe, eleve);
        saveModele();
        updateComponentsGroupeEleve(modele.getGroupe(groupe).getListeEleve());
    }





// --------------------------------------------------------------------------------------------------------------------------------------------------------    

    private void updateComponentsEleveGroupe(ArrayList<Groupe> listeGroupe)
    {
        DefaultListModel model = new DefaultListModel();
        eleveGroupe.setModel(model);

        for (Groupe g : listeGroupe)
        {
            model.addElement(g.getNomGroupe());
        }
    }

    private void initComponentsEE()
    {
        DefaultListModel model = new DefaultListModel();
        eleveEleve.setModel(model);

        for (Eleve e : modele.getEleves())
        {
            model.addElement(e.getNom());
        }
    }


    private void eleveAfficherActionPerformed(java.awt.event.ActionEvent evt) {                                              
        String eleve = eleveEleve.getSelectedValue();
        Eleve e = modele.getEleve(eleve);
        saveModele();
        updateComponentsEleveGroupe(e.getListesGroupes());
    }

    private void eleveSupprActionPerformed(java.awt.event.ActionEvent evt) {
        String eleve = eleveEleve.getSelectedValue();
        String groupe = eleveGroupe.getSelectedValue();
        modele.removeEleveGroupe(groupe, eleve);
        saveModele();
        updateComponents();
        updateComponentsEleveGroupe(modele.getEleve(eleve).getListesGroupes());
    }



    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionGroupe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionGroupe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionGroupe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionGroupe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GestionGroupe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> addEleve;
    private javax.swing.JButton addEleveGroupe;
    private javax.swing.JList<String> addGroupe;
    private javax.swing.JLabel addText;
    private javax.swing.JButton eleveAfficher;
    private javax.swing.JList<String> eleveEleve;
    private javax.swing.JList<String> eleveGroupe;
    private javax.swing.JButton eleveSuppr;
    private javax.swing.JLabel eleveText;
    private javax.swing.JButton groupeAfficher;
    private javax.swing.JList<String> groupeEleve;
    private javax.swing.JList<String> groupeGroupe;
    private javax.swing.JButton groupeSuppr;
    private javax.swing.JLabel groupeText;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    // End of variables declaration//GEN-END:variables
}
